### ISSUE TITLE
Can not edit memos in mobile version

### ISSUE THREAD

**Issue by pythonius21** [mudkipme/MoeMemosAndroid#187] opened 2024-06-17 06:12 UTC
I can edit the memos via web but not in the android version (fdroid and Google play version tested), change memos status to public,workspace and private, still can't edit via Android app.

It gives me an blank error popup
![Screenshot_20240617-081056](https://github.com/mudkipme/MoeMemosAndroid/assets/48410601/016fa2e2-158c-43c8-906f-80d6895c6cea)

**Comment by mudkipme** [comment] 2024-06-17 12:53
I'm unable to reproduce this issue. Could you use a proxy tool to find out the request url & body, and responses happened when you tap the save button?

The access log of your http server may also help.

**Comment by ganeshlab** [comment] 2024-06-17 19:16
I had the same issue. I was using the token to login because the default method wasn't working in the beta. Cleared data on the android app and switched back to default login and now everything works as usual.

**Comment by mudkipme** [comment] 2024-06-19 15:45
"Connection reset by peer" looks like a server panic when handling request. Is there any logs on Memos' side? Do you use any architecture other than amd64?  Did the Memos process or container restarted?

And I'd like to know whether using 0.22.1, 0.22.2 and stable Docker tag could make a different.

**Comment by mudkipme** [comment] 2024-06-19 16:17
> > "Connection reset by peer" looks like a server panic when handling request. Is there any logs on Memos' side? Do you use any architecture other than amd64? Did the Memos process or container restarted?
> > And I'd like to know whether using 0.22.1, 0.22.2 and stable Docker tag could make a different.
> > You may also try connecting to Memos server directly without a reverse proxy and see if there's any logs.
> 
> I can confirm that connecting directly to it does work!

Thanks for the information!

May I see your nginx configuration and nginx version to help reproduce this issue?

**Comment by mudkipme** [comment] 2024-06-20 11:31
I can finally reproduce this issue with Nginx Proxy Manager and curl command to the PATCH request. Further investigation shows the request didn’t reach the handler method of Memos server so there might be something wrong with the echo library or mixing HTTP/GRPC methods.

I’ll try to figure out the exact issue and submit a pull request to Memos if there can be a fix. Otherwise, Moe Memos will switch to Protobuf requests like the web app for 0.22+.

The risk of switching to Protobuf is if there is any API breaking changes in Memos (that’s more likely happen in Protobuf than JSON), Moe Memos will have to upgrade and break support for earlier versions (0.22+).

**Comment by mudkipme** [comment] 2024-06-21 15:44
The fix is merged, please try upgrading the server to `neosmemo/memos:latest` or `0.22.3` docker tag.

**Comment by cdefine** [comment] 2024-06-21 16:59
> The fix is merged, please try upgrading the server to `neosmemo/memos:latest` or `0.22.3` docker tag.

thanks for your fix！！！
i upgrade the server to 0.22.3，most of functions are normal ，but cannot upload image now 。the server response 500

**Comment by mudkipme** [comment] 2024-06-21 20:31
> > The fix is merged, please try upgrading the server to `neosmemo/memos:latest` or `0.22.3` docker tag.
> 
> thanks for your fix！！！ i upgrade the server to 0.22.3，most of functions are normal ，but cannot upload image now 。the server response 500

Is there any error log in Memos or the proxy server?

**Comment by pisceswb** [comment] 2024-06-28 08:07
cannot upload image

**Closed** 2024-08-14 15:39 UTC
Labels: server-side
